language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx
  
  
script:
  - cd $TRAVIS_BUILD_DIR
  - export BUILD_DIR=_build-$TRAVIS_OS_NAME
  - mkdir $BUILD_DIR
  - cd $BUILD_DIR
  - cmake ..
  - make
  